python main.py \
  --backbone resnet18 \
  --enc_layers 6 \
  --dec_layers 6 \
  --hidden_dim 128 \
  --nheads 8 \
  --num_queries 30 \
  --device cuda \
  --dataset_file web \
  --inference_image_path ./datasets/data_web/train2017/000000000014.jpg \
  --weights_path ./output_web/checkpoint.pth \
  --inference_annotations_file ./datasets/data_web/annotations/classes.json
